// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI9gQE_frMevzvNsJ5MmJUHSs7Q2-WNhg',
    appId: '1:342334078135:web:177b7ac6f1ed852730e132',
    messagingSenderId: '342334078135',
    projectId: 'ownnotes-pacha',
    authDomain: 'ownnotes-pacha.firebaseapp.com',
    storageBucket: 'ownnotes-pacha.appspot.com',
    measurementId: 'G-5F6SNMKVPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoO23T7htHu3CH3sz9S-CIg_izurIkEp0',
    appId: '1:342334078135:android:87e6d360dac69c0b30e132',
    messagingSenderId: '342334078135',
    projectId: 'ownnotes-pacha',
    storageBucket: 'ownnotes-pacha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7_s0lh0wRRiqlEPPNKa5wG2KKHF8SEU8',
    appId: '1:342334078135:ios:e226f6210d84da0830e132',
    messagingSenderId: '342334078135',
    projectId: 'ownnotes-pacha',
    storageBucket: 'ownnotes-pacha.appspot.com',
    iosClientId: '342334078135-hqulqilqlhmg9i0u4v5nls1763v84uac.apps.googleusercontent.com',
    iosBundleId: 'com.secondappever.ownnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7_s0lh0wRRiqlEPPNKa5wG2KKHF8SEU8',
    appId: '1:342334078135:ios:47bae6ccab67ac5930e132',
    messagingSenderId: '342334078135',
    projectId: 'ownnotes-pacha',
    storageBucket: 'ownnotes-pacha.appspot.com',
    iosClientId: '342334078135-ka0j7kupq2nk84urklbde6duk1plqfan.apps.googleusercontent.com',
    iosBundleId: 'com.secondappever.ownnotes.RunnerTests',
  );
}
